import { useEffect, useState } from 'react';
import { ArrowDown, ArrowUp, Building2, Eye, Pencil, Plus, Star, Trash2, Users } from 'lucide-react';
import { Link } from 'react-router-dom';
import api, { messageFrom } from '../services/api';
import Pagination from '../components/Pagination';
import RatingStars from '../components/RatingStars';
import { useToast } from '../context/ToastContext';

export function AdminUsers() {
  const [items, setItems] = useState([]); const [meta, setMeta] = useState({}); const [search, setSearch] = useState(''); const [role, setRole] = useState(''); const [page, setPage] = useState(1); const [sort, setSort] = useState('name'); const [order, setOrder] = useState('asc'); const [show, setShow] = useState(false); const [editing, setEditing] = useState(null); const [error, setError] = useState('');
  const load = () => api.get('/admin/users', { params: { search, role, page, limit: 10, sort, order } }).then((res) => { setItems(res.data.data.items); setMeta(res.data.data.pagination); }).catch((err) => setError(messageFrom(err)));
  useEffect(() => { load(); }, [search, role, page, sort, order]);
  const changeSort = (field) => { setPage(1); setOrder(sort === field && order === 'asc' ? 'desc' : 'asc'); setSort(field); };
  const { show: notify } = useToast(); const remove = async (user) => { if (!window.confirm(`Delete ${user.name}?`)) return; try { await api.delete(`/admin/users/${user.id}`); notify('User deleted successfully'); load(); } catch (err) { setError(messageFrom(err)); notify(messageFrom(err), 'error'); } };
  return <><PageTitle eyebrow="ADMINISTRATION" title="People in your workspace" copy="Manage accounts and access levels." action={<button className="button primary" onClick={() => setShow(true)}><Plus size={16} /> Add user</button>} /><div className="admin-toolbar"><TableToolbar icon={Users} placeholder="Search name, email or address" value={search} onChange={(value) => { setPage(1); setSearch(value); }} /><select value={role} onChange={(e) => { setPage(1); setRole(e.target.value); }}><option value="">All roles</option><option>USER</option><option>OWNER</option><option>ADMIN</option></select></div>{error && <div className="alert error">{error}</div>}<section className="panel table-wrap"><table><thead><tr><SortHeader label="Name" field="name" sort={sort} order={order} onClick={changeSort} /><SortHeader label="Email" field="email" sort={sort} order={order} onClick={changeSort} /><SortHeader label="Address" field="address" sort={sort} order={order} onClick={changeSort} /><th>Role</th><th>Actions</th></tr></thead><tbody>{items.map((user) => <tr key={user.id}><td><div className="table-person"><span className="avatar soft">{user.name.charAt(0)}</span><strong>{user.name}</strong></div></td><td>{user.email}</td><td>{user.address}</td><td><span className="role-badge">{user.role}</span></td><td><div className="row-actions"><Link className="icon-button" to={`/admin/users/${user.id}`} aria-label={`View ${user.name}`}><Eye size={16} /></Link><button className="icon-button" onClick={() => setEditing(user)} aria-label={`Edit ${user.name}`}><Pencil size={16} /></button><button className="icon-button" onClick={() => remove(user)} aria-label={`Delete ${user.name}`}><Trash2 size={16} /></button></div></td></tr>)}</tbody></table>{!items.length && <div className="empty-inline">No users found</div>}</section><Pagination {...meta} onChange={setPage} />{(show || editing) && <UserForm initial={editing} close={() => { setShow(false); setEditing(null); }} refresh={load} />}</>;
}

export function AdminStores() {
  const [items, setItems] = useState([]); const [meta, setMeta] = useState({}); const [search, setSearch] = useState(''); const [category, setCategory] = useState(''); const [minRating, setMinRating] = useState(''); const [page, setPage] = useState(1); const [sort, setSort] = useState('name'); const [order, setOrder] = useState('asc'); const [show, setShow] = useState(false); const [editing, setEditing] = useState(null); const [error, setError] = useState('');
  const load = () => api.get('/admin/stores', { params: { search, category, minRating, page, limit: 10, sort, order } }).then((res) => { setItems(res.data.data.items); setMeta(res.data.data.pagination); }).catch((err) => setError(messageFrom(err)));
  useEffect(() => { load(); }, [search, category, minRating, page, sort, order]);
  const changeSort = (field) => { setPage(1); setOrder(sort === field && order === 'asc' ? 'desc' : 'asc'); setSort(field); };
  const { show: notify } = useToast(); const remove = async (store) => { if (!window.confirm(`Delete ${store.name}?`)) return; try { await api.delete(`/admin/stores/${store.id}`); notify('Store deleted successfully'); load(); } catch (err) { setError(messageFrom(err)); notify(messageFrom(err), 'error'); } };
  return <><PageTitle eyebrow="DIRECTORY MANAGEMENT" title="Registered stores" copy="Keep the store directory accurate and useful." action={<button className="button primary" onClick={() => setShow(true)}><Plus size={16} /> Add store</button>} /><div className="admin-toolbar"><TableToolbar icon={Building2} placeholder="Search stores or locations" value={search} onChange={(value) => { setPage(1); setSearch(value); }} /><select value={category} onChange={(e) => { setPage(1); setCategory(e.target.value); }}><option value="">All categories</option><option>Electronics</option><option>Grocery</option><option>Clothing</option><option>Restaurants</option><option>Cafes</option><option>Furniture</option><option>Pharmacy</option><option>Sports</option><option>Beauty</option><option>Automotive</option></select><select value={minRating} onChange={(e) => { setPage(1); setMinRating(e.target.value); }}><option value="">Any rating</option><option value="5">At least 5</option><option value="4">At least 4</option><option value="3">At least 3</option></select></div>{error && <div className="alert error">{error}</div>}<section className="panel table-wrap"><table><thead><tr><SortHeader label="Store" field="name" sort={sort} order={order} onClick={changeSort} /><SortHeader label="Address" field="address" sort={sort} order={order} onClick={changeSort} /><th>Owner</th><th>Rating</th><th>Actions</th></tr></thead><tbody>{items.map((store) => <tr key={store.id}><td><strong>{store.name}</strong><small className="table-sub">{store.email}</small></td><td>{store.address}</td><td>{store.owner?.name ?? 'Unassigned'}</td><td><div className="rating-inline"><RatingStars value={Math.round(store.averageRating ?? 0)} />{store.averageRating ?? 'No ratings yet'}</div></td><td><div className="row-actions"><button className="icon-button" onClick={() => setEditing(store)} aria-label={`Edit ${store.name}`}><Pencil size={16} /></button><button className="icon-button" onClick={() => remove(store)} aria-label={`Delete ${store.name}`}><Trash2 size={16} /></button></div></td></tr>)}</tbody></table>{!items.length && <div className="empty-inline">No stores found</div>}</section><Pagination {...meta} onChange={setPage} />{(show || editing) && <StoreForm initial={editing} close={() => { setShow(false); setEditing(null); }} refresh={load} />}</>;
}

export function AdminRatings() {
  const [items, setItems] = useState([]); const [meta, setMeta] = useState({}); const [search, setSearch] = useState(''); const [page, setPage] = useState(1); const [sort, setSort] = useState('createdAt'); const [order, setOrder] = useState('desc'); const [error, setError] = useState('');
  const load = () => api.get('/admin/ratings', { params: { search, page, limit: 10, sort, order } }).then((res) => { setItems(res.data.data.items); setMeta(res.data.data.pagination); }).catch((err) => setError(messageFrom(err)));
  useEffect(() => { load(); }, [search, page, sort, order]);
  const changeSort = (field) => { setPage(1); setOrder(sort === field && order === 'asc' ? 'desc' : 'asc'); setSort(field); };
  return <><PageTitle eyebrow="MODERATION" title="All submitted ratings" copy="Review the latest feedback across the platform." /><TableToolbar icon={Star} placeholder="Search user, store, or review" value={search} onChange={(value) => { setPage(1); setSearch(value); }} />{error && <div className="alert error">{error}</div>}<section className="panel table-wrap"><table><thead><tr><th>User</th><th>Store</th><SortHeader label="Rating" field="rating" sort={sort} order={order} onClick={changeSort} /><th>Review</th><SortHeader label="Submitted" field="createdAt" sort={sort} order={order} onClick={changeSort} /></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><strong>{item.user.name}</strong><small className="table-sub">{item.user.email}</small></td><td>{item.store.name}</td><td><div className="rating-inline"><RatingStars value={item.rating} />{item.rating}/5</div></td><td>{item.comment || 'No written review'}<small className="table-sub">{new Date(item.createdAt).toLocaleDateString()}</small></td></tr>)}</tbody></table>{!items.length && <div className="empty-inline">No ratings found</div>}</section><Pagination {...meta} onChange={setPage} /></>;
}

function SortHeader({ label, field, sort, order, onClick }) { const active = sort === field; return <th><button className="sort-button" onClick={() => onClick(field)}>{label}{active && (order === 'asc' ? <ArrowUp size={13} /> : <ArrowDown size={13} />)}</button></th>; }
function PageTitle({ eyebrow, title, copy, action }) { return <div className="page-heading"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="muted">{copy}</p></div>{action}</div>; }
function TableToolbar({ icon: Icon, placeholder, value, onChange }) { return <div className="toolbar"><div className="search-field"><Icon size={18} /><input value={value} onChange={(e) => onChange(e.target.value)} placeholder={placeholder} /></div></div>; }
function UserForm({ initial, close, refresh }) { const { show: notify } = useToast(); const [form, setForm] = useState({ name: initial?.name ?? '', email: initial?.email ?? '', address: initial?.address ?? '', password: '', role: initial?.role ?? 'USER' }); const [error, setError] = useState(''); const editing = Boolean(initial); const submit = async (e) => { e.preventDefault(); try { await api[editing ? 'put' : 'post'](editing ? `/admin/users/${initial.id}` : '/admin/users', form); notify(editing ? 'User updated successfully' : 'User created successfully'); refresh(); close(); } catch (err) { setError(messageFrom(err)); notify(messageFrom(err), 'error'); } }; return <Modal title={editing ? 'Edit workspace user' : 'Add workspace user'} close={close}><form className="form-grid" onSubmit={submit}>{error && <div className="alert error full">{error}</div>}<Input label="Full name" name="name" form={form} setForm={setForm} /><Input label="Email" name="email" form={form} setForm={setForm} type="email" /><Input label="Address" name="address" form={form} setForm={setForm} />{!editing && <Input label="Password" name="password" form={form} setForm={setForm} type="password" />}<label className="field"><span>Role</span><select value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value })}><option>USER</option><option>OWNER</option><option>ADMIN</option></select></label><button className="button primary full">{editing ? 'Save changes' : 'Create user'}</button></form></Modal>; }
function StoreForm({ initial, close, refresh }) { const { show: notify } = useToast(); const [form, setForm] = useState({ name: initial?.name ?? '', email: initial?.email ?? '', address: initial?.address ?? '', category: initial?.category ?? 'Electronics', description: initial?.description ?? '' }); const [error, setError] = useState(''); const editing = Boolean(initial); const submit = async (e) => { e.preventDefault(); try { await api[editing ? 'put' : 'post'](editing ? `/admin/stores/${initial.id}` : '/admin/stores', form); notify(editing ? 'Store updated successfully' : 'Store created successfully'); refresh(); close(); } catch (err) { setError(messageFrom(err)); notify(messageFrom(err), 'error'); } }; return <Modal title={editing ? 'Edit store' : 'Add a store'} close={close}><form className="form-grid" onSubmit={submit}>{error && <div className="alert error full">{error}</div>}<Input label="Store name" name="name" form={form} setForm={setForm} /><Input label="Email" name="email" form={form} setForm={setForm} type="email" /><Input label="Address" name="address" form={form} setForm={setForm} /><Input label="Description" name="description" form={form} setForm={setForm} /><label className="field"><span>Category</span><select value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })}><option>Electronics</option><option>Grocery</option><option>Clothing</option><option>Restaurants</option><option>Cafes</option><option>Furniture</option><option>Pharmacy</option><option>Sports</option><option>Beauty</option><option>Automotive</option></select></label><button className="button primary full">{editing ? 'Save changes' : 'Create store'}</button></form></Modal>; }
function Input({ label, name, form, setForm, type = 'text' }) { return <label className="field"><span>{label}</span><input required type={type} value={form[name]} onChange={(e) => setForm({ ...form, [name]: e.target.value })} /></label>; }
function Modal({ title, close, children }) { return <div className="modal-backdrop"><div className="modal"><button className="modal-close" onClick={close}>×</button><p className="eyebrow">ADMIN TOOL</p><h2>{title}</h2>{children}</div></div>; }
